language: java
jdk:
  - openjdk11
services:
  - postgresql
  - docker
env:
  - global:
      - secure: "hhuatWEa1s7wQ3f4SZSmNG/Hhqk4RJuL8GSHpkpz+0Cx2jC0z14fg+eVM4r2WCLSDA8gYCNk9SPUK/efZFb10Ln+i1pV3dR/OAiO+AEWoPgbvYulbnxZZofXkKXR4VIWqabtBDVAGdx2K7gf2cZyrmneU+gmaegAn95nIi0xaJ49XzzcAcVa9FZJRR3wacBJvHVmQ2YaK00FgqKNtt74vjz10u7vIoYS3OSBW46sjTnAijpn41L6aPz67tqE2BNvAgU1g4LwXKTPFdca2W4jE4tF4ojasUHbngVVylSfsCb1BnMLSZZHXwPSBzQT59Zpc6EEpuaZxO/P/sSR1n4Fkur9FbDHW1tv3sWHN1UQsQLNug8uABve753r1Z4xG5QH5TApOB7yrpDA+W2+OjBEAz6OXZxFFVYzPEYYiFoEeq3HlKp6w9zieYzILT4Xr/5W7FQCcEvsAg5uZoe2E8xAK4CuUZpMjQCNcNvkIUz8K0x97/3o2Bjz+6G5kh1oTabCBUFWA12WXxNrzYtBlDHR40jY9r9rmwWWkTgYOWVLquzAZim6jwmC5Z+CeXdp3pPk9gqwlOSLsWBsAAwnGmvQN9XBao+z7+IWYmG0Q6gLDa+HWN63XYD1N6no4I0L8SPDaza7xBHadDVY8XgUXVZw0xeZkEgn95R7R6U9Qcn6XUc="
      - secure: "pUlGNz13tAN6DdUuzvCqzOqQgX28P+uRTZyD2ndYe+A7I7UCLtjVqZBPRo2rL2W6mBPvTthMvO5iVAZblZEKukg+Kk+Wu4DCOMps0uvK2CY7HEe0Jf6I9LkUoVIjyuxzhCPI/PCpSw1bdZumBFo3yOjyhWRt9wcEQBgyq3CrvxYLYsFq8Ne6u3ClMSFDLCZ+BVj5TZDVgc9/cKM1KoefmBXjdL6VT2bPzq3XW9FRx+wYWdBZoZKRWuogMjXuzl9oyYq5FLZEQYD2eCuPLGEZ9PYuZKGq2blQ+Bc2VFazsgsnmDu3+tP7dqt8KfQcZAV993Tv8qzP6ACJ9ztoFk6egVxm7aEpZigh9T1mN5lxMS/um4iAL8hUH/I9L4HfE2uh3w5vXlr1GbZdBGcYt9iYc9nnyVUm/1CgpkZy9U3W+w6whCChKgDisXOCpl23vrGAHGyRGKrbAqD7CqZ3b+Zgjhu25Sk3E6UFk3447d8FH05brr792FgXF76LaQTifTKe0lGFIWQ1yaJLXog3oxdIZWQZuvJXPZzeTjbX19i0VwX0fSg6lqA4LbY8PnEgG2vrCgzSgZS0E5/PtrJOvix2y7Pe9hkIVmKfWlzvey04UTmgEZ8NEtl/S9Bh7KTdbr+QJqWIZEWZOmKAEzzpfATkChOznpoVn35pjIS3OCWA8Xo="
      - secure: "TKC6ZHVrTGtO0DfRGWtilMVW9qpyCCg19+OXDKaoGW1UHq7NYsucvmh5ATOgqKDufktW//KX2BXHJEtUHodjtHD5rsLCD03hbeHi8eHYn4ZOODX11o9yPEhIAOJgt/vPEhyvLLHHsMw1gt3X9oUCXPlKLO5thTxy7PYs5FM7pVd9q/LGEMt3aldDDwAS4d7pbv3o6HrBheauVepFTiViM4PomMV1T62wCMarAMU+S3zoS2e2cd9XOGuksFV67e6jAoyQwf0kuSHXqmTW9C6UGgRLK79FhbbYIBTnt4DAyntA5d3JuGAgWfc1mGug3KBb/AvJbEUjihI8n3nXel7ZmDBlKKfEQZsOtALt4eKHOp2CHEXW3KaDsRPIFE8aToDYGfM6FWKBXlLLCdWdp5+sLmQD2deV2TvPW4+RZCWwSCGn3AjhceaRKH3Nwr/HISEN9/1hWFiharINfDCvdst616PVtj9yvV5m8w9/wIQubRlti1APBb+8qYNlPmP3S2ysgLhl0zL0uo8/PTy6uA6+D/z6Km6RQ+2WtNIb0DAvTHiyXLHaOAkFKz2sbL4mK9Ypx4fE+thx09ZLUsFX3+wkAKdE/QShoS/RskFom6HwyOCkQ/IkEyNaqfnMPHq1wsrtsGJS7einaZ6UL71Q6lS+1v4JmtF2wnwy45dCBqumE04="
cache:
  directories:
    - $HOME/.m2
before_script:
  - psql -c "CREATE USER $USERNAME WITH PASSWORD '$PASSWORD';" -U postgres
  - psql -c "ALTER ROLE $USERNAME SUPERUSER"
  - psql -c "CREATE DATABASE $DB;" -U postgres
install: true
script:
  - "mvn clean flyway:migrate jooq-codegen:generate install"
after_success:
  -  docker build -t my_example_app .
  - if [ "$TRAVIS_BRANCH" == "master" ]; then echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin; docker push my_example_app; fi
